POST http://localhost:8081/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGUxQDEzMy5jb20iLCJleHAiOjE3MjkwMzkwNzIsInVzZXJJZCI6MX0.dk4Zm0OJyCalGiDMXf7q2EDxbtZ7Tmvh6gviyifrEWg

{
  "name": "Test Event",
  "description": "This is a test event",
  "location": "Test Location",
  "dateTime": "2035-01-01T23:59:59Z"
}