POST http://localhost:8081/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGUxQDEzMy5jb20iLCJleHAiOjE3MjkwMzkwNzIsInVzZXJJZCI6MX0.dk4Zm0OJyCalGiDMXf7q2EDxbtZ7Tmvh6gviyifrEWg