apiVersion: v1
kind: Service
metadata:
  name: kitex-client
spec:
  ports:
    - port: 80
      targetPort: 8888
  selector:
    app: kitex-client

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitex-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitex-client
      version: v1
  template:
    metadata:
      labels:
        app: kitex-client
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: kitex-client
          image: kitex-example/proxyless
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
          # specify the service name for this instance
          # specify to "benchmark-client" if want to deploy benchmark
          - name: MY_SERVICE_NAME
            value: kitex-client #benchmark-client
          - name: mesh_mode
            value: kitex-proxyless
          # POD_NAMESPACE, POD_NAME, INSTANCE_IP will be used in the bootstrap function of xds
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kitex-client
spec:
  host: kitex-client.svc.cluster.local
  trafficPolicy:
    tls:
      # disable the mTLS
      mode: DISABLE